"""
Extract a complete SubCode label reference from NHS England's illustrative TAC workbook.

Purpose: dim_subcode is only seeded for 5 of the 28 real TAC worksheets (TAC02, TAC06, TAC07,
TAC08, TAC09) even though every worksheet has real rows in the raw data. This script parses
data/raw/TAC_illustrative_2023-24.xlsx -- NHS England's own schema reference file -- and
generates the missing dim_subcode seed rows plus a markdown reference table, covering every
worksheet NOT already hand-curated in sql/schema/create_tables_mysql.sql.

Usage: python python/ingestion/build_subcode_reference.py
Output: data/processed/subcode_reference_seed.sql, data/processed/subcode_reference.md
        (both regenerable, hand-review before merging into committed files)
"""

import logging
import re
from pathlib import Path

import openpyxl

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)-8s %(message)s")
log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
ILLUSTRATIVE_FILE = REPO_ROOT / "data" / "raw" / "TAC_illustrative_2023-24.xlsx"
OUT_DIR = REPO_ROOT / "data" / "processed"
SQL_OUT = OUT_DIR / "subcode_reference_seed.sql"
MD_OUT = OUT_DIR / "subcode_reference.md"

# Worksheets already hand-curated in sql/schema/create_tables_mysql.sql -- skip so we
# never override the reviewed descriptions, expected_sign, is_subtotal, analytics_category
# already in use by v_expenditure_breakdown's PAY/NON_PAY grouping.
ALREADY_SEEDED_WORKSHEETS = {
    "TAC02 SoCI", "TAC06 Op Inc 1", "TAC07 Op Inc 2", "TAC08 Op Exp", "TAC09 Staff",
}

# TAC14X RoU Assets PY reuses the exact same SubCode values as TAC14A RoU Assets (it's the
# prior-year comparative of the same schedule) -- dim_subcode.sub_code is a single global
# PRIMARY KEY, so seeding both would collide. TAC14A's labels already cover these SubCodes.
SKIP_WORKSHEETS = ALREADY_SEEDED_WORKSHEETS | {"TAC14X RoU Assets PY"}

SUBCODE_RE = re.compile(r"^[A-Z]{2,4}\d{3,5}[A-Z]?$")
SIGN_TOKENS = {"+", "-", "+/-"}


def clean_worksheet_name(raw_name: str) -> str:
    return raw_name.replace("&amp;", "&")


def clean_label(raw_label: str) -> str:
    return re.sub(r"\s+", " ", raw_label).strip()


def is_subtotal_label(label: str) -> bool:
    stripped = label.strip()
    letters_only = re.sub(r"[^A-Za-z]", "", stripped)
    return stripped.lower().startswith("total") or (
        len(letters_only) > 3 and letters_only.isupper()
    )


def infer_unit(worksheet_name: str, label: str) -> str:
    if "WTE" in label.upper():
        return "No."
    return "£000"


def extract_worksheet_subcodes(ws) -> list[dict]:
    rows = []
    seen = set()
    for row in ws.iter_rows(values_only=True):
        subcode = None
        for value in row:
            if isinstance(value, str) and SUBCODE_RE.match(value.strip()):
                subcode = value.strip()
        if not subcode or subcode in seen:
            continue

        label = row[1] if isinstance(row[1], str) and row[1].strip() else None
        if label is None:
            label = next(
                (v.strip() for v in row if isinstance(v, str) and v.strip() not in SIGN_TOKENS
                 and not SUBCODE_RE.match(v.strip())),
                None,
            )
        if label is None:
            log.warning("  Skipping %s -- no label found on its row", subcode)
            continue

        sign = next((v.strip() for v in row if isinstance(v, str) and v.strip() in SIGN_TOKENS), None)

        seen.add(subcode)
        rows.append({
            "sub_code": subcode,
            "description": clean_label(label),
            "expected_sign": sign,
        })
    return rows


def build_reference() -> dict[str, list[dict]]:
    log.info("Loading %s ...", ILLUSTRATIVE_FILE)
    wb = openpyxl.load_workbook(ILLUSTRATIVE_FILE, data_only=True)

    reference = {}
    for sheet_name in wb.sheetnames:
        if sheet_name == "Intro":
            continue
        worksheet_name = clean_worksheet_name(sheet_name)
        if worksheet_name in SKIP_WORKSHEETS:
            log.info("  %-30s skipped", worksheet_name)
            continue
        rows = extract_worksheet_subcodes(wb[sheet_name])
        log.info("  %-30s %d subcodes extracted", worksheet_name, len(rows))
        reference[worksheet_name] = rows
    return reference


def write_sql(reference: dict[str, list[dict]]) -> None:
    lines = [
        "-- Auto-generated by python/ingestion/build_subcode_reference.py",
        "-- Source: data/raw/TAC_illustrative_2023-24.xlsx",
        "-- Review before merging into sql/schema/create_tables_mysql.sql / sql/views/",
        "USE nhs_silver;",
        "",
    ]
    for worksheet_name, rows in reference.items():
        if not rows:
            continue
        lines.append(f"-- {worksheet_name}")
        lines.append("INSERT INTO dim_subcode (sub_code, worksheet_name, description, expected_sign, unit, is_subtotal, analytics_category) VALUES")
        value_lines = []
        for r in rows:
            sign_sql = f"'{r['expected_sign']}'" if r["expected_sign"] else "NULL"
            desc_sql = r["description"].replace("'", "''")
            unit = infer_unit(worksheet_name, r["description"])
            subtotal = 1 if is_subtotal_label(r["description"]) else 0
            value_lines.append(
                f"    ('{r['sub_code']}', '{worksheet_name}', '{desc_sql}', {sign_sql}, '{unit}', {subtotal}, NULL)"
            )
        lines.append(",\n".join(value_lines) + ";")
        lines.append("")

    SQL_OUT.parent.mkdir(parents=True, exist_ok=True)
    SQL_OUT.write_text("\n".join(lines), encoding="utf-8")
    log.info("Wrote %s", SQL_OUT)


def write_markdown(reference: dict[str, list[dict]]) -> None:
    lines = ["# Full SubCode Reference (generated)", "",
              "Generated from `data/raw/TAC_illustrative_2023-24.xlsx`. Covers every TAC worksheet",
              "not already documented by hand in `agent_docs/data_dictionary.md`.", ""]
    for worksheet_name, rows in reference.items():
        if not rows:
            continue
        lines.append(f"## {worksheet_name}")
        lines.append("")
        lines.append("| SubCode | Description | Sign |")
        lines.append("|---------|-------------|------|")
        for r in rows:
            lines.append(f"| `{r['sub_code']}` | {r['description']} | {r['expected_sign'] or ''} |")
        lines.append("")

    MD_OUT.parent.mkdir(parents=True, exist_ok=True)
    MD_OUT.write_text("\n".join(lines), encoding="utf-8")
    log.info("Wrote %s", MD_OUT)


def main() -> None:
    reference = build_reference()
    total = sum(len(rows) for rows in reference.values())
    log.info("Total new SubCodes extracted: %d across %d worksheets", total, len(reference))
    write_sql(reference)
    write_markdown(reference)


if __name__ == "__main__":
    main()
